### PR TITLE
Completely remove traces of AuthorFilterAPI

### PR DESCRIPTION
**Pull request by JoshOrndorff**
Solves #25 
This PR removes all traces of the old `AuthorFilterAPI` leaving only the `NimbusApi` introduced in #21

### CODE REVIEW

**Review by librelois — APPROVED** [review]

**Comment by JoshOrndorff** [comment]
@librelois @nbaztec I believe this one is also ready. Is there anything blocking it that you know of?

**Comment by librelois** [comment]
@JoshOrndorff I think we still need a client able to manage old runtimes, some actors may need to replay past blocks.

**Comment by JoshOrndorff** [comment]
This API is not used when importing or executing blocks. It is only used prior to authoring a block to predict whether you will be eligible.

**Comment by librelois** [comment]
> This API is not used when importing or executing blocks. It is only used prior to authoring a block to predict whether you will be eligible.

You are right, I remember our discussions on this now, ok I'll resolve the conflict and merge.

**Comment by JoshOrndorff** [comment]
@librelois I've updated this PR with `main` again. I can't push here because I don't have the rights to this repo. The commit I made is https://github.com/JoshOrndorff/nimbus/commit/7c9be57e98c043db2cd838e593784ee67c904931

Can you please cherry=pick it and then merge this one? :)

**Comment by JoshOrndorff** [comment]
:rocket:

**Pull request merged**
