### PR TITLE
Use little endian instead of big endian for index bytes (author slot filter fix)

### PR DESCRIPTION
**Pull request by peektism**
This fixes the bug we saw wherein the same randomness was produced for every iteration.

The fix changes it from using big endian to little endian. We want to sample the least significant bits because the most significant bits do not change in every iteration

After this PR, we use the first 2 bytes of `index.to_le_bytes()` and the first 4 bytes of `seed.to_be_bytes()`

The bug was introduced in https://github.com/PureStake/nimbus/pull/76

### CODE REVIEW

**Comment by goozang-records** [comment]
`seed` is the slot number. What is the slot number at right now? We need to choose whatever bytes are changing, is it the 4 most significant bytes, 4 least significant bytes, or neither

**Comment by crystalin** [comment]
For the seed, it doesn't matter, it is 4 bytes, so no matter if you use le or be

**Comment by goozang-records** [comment]
Will reopen against main and cherrypick into 9.31 update branch

**Comment by goozang-records** [comment]
Closed because was open against 9.29 branch and stuff changed since then. Didn't feel like dealing with merge conflicts.

**Pull request closed without merging**
