### PR TITLE
v0.9.19 update

### PR DESCRIPTION
**Pull request by notlesh**
This is a merge back into `main` of the relevant changes of the v0.9.19 dependency update.

Currently, it is just a clone of the `moonbeam-polkadot-v0.9.19` branch but can diverge later (e.g. to restore the upstream branches).

We (I) failed to do this with the `v0.9.18` update, so this includes both .18 and .19.

### CODE REVIEW

**Comment by crystalin** [comment]
v0.9.18 wasn't merged ? Why not simply merge the branch and start from there ?

**Comment by notlesh** [comment]
> v0.9.18 wasn't merged ? Why not simply merge the branch and start from there ?

At the time we rolled out Moonbeam's deps update, Nimbus needed some small fixes for its node template. I think @nbaztec took care of that.

We could merge the v0.9.18 branch and start from there as you describe, it wouldn't take much effort. Let's discuss that tomorrow.

**Comment by notlesh** [comment]
@librelois when merging back into main, which dependency repos/branches do we want? Do you think it's ok to point to purestake repos and keep the `moonbeam-polkadot-vX.Y.Z` branches?

**Comment by librelois** [comment]
> @librelois when merging back into main, which dependency repos/branches do we want? Do you think it's ok to point to purestake repos and keep the `moonbeam-polkadot-vX.Y.Z` branches?

I think that for our own repositories (nimbus and crowdloan-rewards), we shoud upgrade dependencies in the main/master branch before our `moonbeam-polkadot-*` branch. This is the order in which joshy did it.

So, here the best is to create a specific branch to upgrade nimbus main to 0.9.19, then when it will be merged, we will take care of the branch for moonbeam.

**Comment by librelois** [comment]
I think we can close this PR and merge #51 instead

**Pull request merged**
