### PR TITLE
time-based slots and non-parachain support

### PR DESCRIPTION
**Pull request by JoshOrndorff**
Solves #3 

This PR (currently WIP) adds an implementation of Substrates [`SlotWorker` trait](https://crates.parity.io/sc_consensus_slots/trait.SlotWorker.html) that works with Nimbus.

This will allow standalone blockchains (not parachains) to use nimbus in production.

This PR will also add an example of using nimbus in this way in the template node.

### CODE REVIEW

**Comment by JoshOrndorff** [comment]
@librelois I wonder if you would be willing to look at my code here for a few minutes. I am really close to having nimbus work in non-parachain context. But I am stuck on a lifetime issue.

EDIT: Nevermind, it was just a silly mistake. But writing a question to you really seemed to get me unstuck :)

**Comment by JoshOrndorff** [comment]
Okay, this is basically working. From here on it is just cleanup and refactoring.

**Comment by librelois** [comment]
@JoshOrndorff can you merge master then tag me when it's done, then I'll review :)

**Comment by JoshOrndorff** [comment]
Sorry, I don't have time for this now. I had time for it six months ago. Plus I don't know how it will interact with the vrf-related changes that have gone in in the meantime.

**Pull request closed without merging**
